language: python
node_js: node  # latest stable Node.js release
python: 3.6
cache:
  directories:
    - "$HOME/.cache/pip"
    - node_modules
install:
  - ./run.sh install
  - ./run.sh install_dev
script:
  - pre-commit run --all-files
  - ./run.sh test_ludochaordic
notifications:
  email:
    on_success: never
