language: python
python: 3.6
install:
  - ./run.sh install
  - ./run.sh install_dev
script:
  - pre-commit run --all-files
  - ./run.sh test_ludochaordic
notifications:
  email:
    on_success: never
